site_name: Streamlit Chat Application Documentation
site_description: A production-ready conversational AI application with advanced language model capabilities
site_author: Your Organization
site_url: https://<your-domain>/docs

docs_dir: docs
site_dir: site

theme: readthedocs

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quickstart.md
      - Installation: getting-started/installation.md
      - First Steps: getting-started/first-steps.md
  - User Guide:
      - Chat Interface: user-guide/chat-interface.md
      - PDF Analysis: user-guide/pdf-analysis.md
      - Image Generation: user-guide/image-generation.md
      - Search Features: user-guide/search-features.md
  - Architecture:
      - Overview: architecture/overview.md
      - Services: architecture/services.md
      - Controllers: architecture/controllers.md
      - Tools: architecture/tools.md
  - API Reference:
      - Services API: api/services.md
      - Controllers API: api/controllers.md
      - Tools API: api/tools.md
      - Models: api/models.md
  - Configuration:
      - Environment Variables: configuration/environment.md
      - Model Configuration: configuration/models.md
      - UI Configuration: configuration/ui.md
  - Deployment:
      - Docker Deployment: deployment/docker.md
      - Production Setup: deployment/production.md
      - Scaling: deployment/scaling.md
  - Development:
      - Development Setup: development/setup.md
      - Contributing: development/contributing.md
      - Testing: development/testing.md
  - Troubleshooting: troubleshooting.md

# plugins:
#   - search
#   - minify:
#       minify_html: true

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - pymdownx.tabbed:
#       alternate_style: true
#   - admonition
#   - pymdownx.details
#   - attr_list
#   - md_in_html
#   - toc:
#       permalink: true

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/tuttlebr/streamlit-chatbot
