site_name: Streamlit Chat Application Documentation
site_description: A production-ready conversational AI application with advanced language model capabilities
site_author: Your Organization
site_url: https://<your-domain>/docs

docs_dir: docs
site_dir: site

theme: readthedocs

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quickstart.md
      - Installation: getting-started/installation.md
      - First Steps: getting-started/first-steps.md
  - User Guide:
      - Chat Interface: user-guide/chat-interface.md
      - PDF Analysis: user-guide/pdf-analysis.md
      - PDF Context Switching: user-guide/pdf_context_switching.md
      - Image Generation: user-guide/image-generation.md
      - Search Features: user-guide/search-features.md
  - Architecture:
      - Overview: architecture/overview.md
      - Services: architecture/services.md
  - API Reference:
      - Services: api/services.md
      - Controllers: api/controllers.md
      - Tools: api/tools.md
      - Streaming: api/streaming.md
  - Configuration:
      - Environment Variables: configuration/environment.md
      - Model Configuration: configuration/models.md
  - Deployment:
      - Docker Setup: deployment/docker.md
  - FAQ: faq.md
  - Troubleshooting: troubleshooting.md

plugins:
  - search
  - mermaid2
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - codehilite
  - tables
  - toc:
      permalink: true
  - mermaid2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tuttlebr/streamlit-chatbot
