[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"

[server]
headless = true
runOnSave = false
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 200
maxUploadSize = 200
disconnectedSessionTTL = 3600

[theme]
base = "dark"
primaryColor = '#76b900'
backgroundColor = '#18191a'
secondaryBackgroundColor = '#403e41'
font = "nvidia-sans"
headingFont = "nvidia-sans"

[[theme.fontFaces]]
family = "nvidia-sans"
style = "normal"
url = "https://brand-assets.cne.ngc.nvidia.com/assets/fonts/nvidia-sans/1.0.0/NVIDIASans_Rg.woff2"

[[theme.fontFaces]]
family = "nvidia-sans"
style = "italic"
url = "https://brand-assets.cne.ngc.nvidia.com/assets/fonts/nvidia-sans/1.0.0/NVIDIASans_Lt.woff2"

[ui]
hideTopBar = true

[runner]
fastReruns = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(filename)s:%(lineno)d %(message)s"
