[browser]
gatherUsageStats = false

[client]
showErrorDetails = false

[server]
runOnSave = true
maxUploadSize = 100
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 200
enableWebsocketCompression = false
disconnectedSessionTTL = 3600

[theme]
base = "dark"
primaryColor = "#76b900"
backgroundColor="#18191a"
secondaryBackgroundColor="#403e41"

[ui]
hideTopBar = true

[runner]
fastReruns = false

[logger]
level = "error"
