# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        exclude: |
          docker/app/mkdocs.yml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args:
          [
            "--line-length=79",
            "--preview",
            "--enable-unstable-feature",
            "string_processing",
          ]
        additional_dependencies: ["click==8.0.4"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          [
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parenthese",
            "--line-width=79",
            "--ws",
            "--skip=third_party",
          ]
  - repo: https://github.com/tuttlebr/nv-pre-commit
    rev: v0.0.5 # Use the ref you want to point at
    hooks:
      - id: detect-nv-keys
        exclude: docker/app/docs/gpu-glossary/.*\.md$
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1 # Use the latest version available
    hooks:
      - id: autoflake
        args:
          [
            --remove-all-unused-imports,
            --remove-unused-variables,
            --ignore-init-module-imports,
            --in-place,
          ]
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.7
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unreachable]
  # - repo: https://github.com/asottile/dead
  #   rev: v2.1.0
  #   hooks:
  #     - id: dead
  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        entry: npx lint-staged
        language: system
        pass_filenames: false
        stages: [commit]
