name: streamlit-chatbot
volumes:
  ssl_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: nginx/ssl

services:
  app:
    image: streamlit-chatbot:local
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: app
    environment:
      WATCHMAN_VERSION: none
    shm_size: 16G
    volumes:
      - ./tmp:/tmp
    user: "1000:1000"
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - chatbot-network

  docs:
    image: streamlit-chatbot-docs:local
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: docs
    ports:
      - "8001:8001"
    volumes:
      - ./docker/app/docs:/app/docs:ro
    restart: unless-stopped
    networks:
      - chatbot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
      - ssl_certs:/etc/nginx/ssl:ro
    depends_on:
      - app
      - docs
    restart: unless-stopped
    networks:
      - chatbot-network

  jupyter:
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: jupyter
    image: jupyter/notebook:latest
    working_dir: /workspace
    ports:
      - "8888:8888"
    volumes:
      - ./tmp:/workspace
networks:
  chatbot-network:
    driver: bridge
