[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain==0.3.25",
    "langchain-openai==0.3.23",
    "openai==1.86.0",
    "pillow==11.2.1",
    "pillow-heif==0.22.0",
    "pymilvus==2.5.7",
    "pytz==2025.2",
    "streamlit==1.45.1",
]
